# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PointCreator
                                 A QGIS plugin
 This plugin create point by coordinate
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-18
        copyright            : (C) 2022 by Danil Skryl
        email                : danskrbiz@yandex.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PointCreator class from file PointCreator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .point_creator import PointCreator
    return PointCreator(iface)
